package ru.practicum.ewm.event.client;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import ru.practicum.ewm.event.dto.LocationAutoRequest;
import ru.practicum.ewm.dto.LocationFullDtoOut;

@FeignClient(
        name = "location-service",
        path = "/locations"
)
public interface LocationClient {

    @GetMapping("/{id}")
    LocationFullDtoOut getLocationById(@PathVariable("id") Long id);

    // внутренний endpoint для main-service
    @PostMapping("/auto")
    LocationFullDtoOut getOrCreateAutoGenerated(@RequestBody LocationAutoRequest dto);
}